name: Runing Test

on: [push]

jobs:
   test-portforyou:
      runs-on: [self-hosted, linux, x64, nodejs]
      steps:
         - uses: actions/checkout@v2
           with:
              fetch-depth: 1
         - uses: actions/setup-node@v1
           with:
              node-version: 16
         - run: yarn
         - run: yarn lint
         - run: yarn check-ts
